$(document).ready(function () {
  // 1. Core Event Handler: Runs when a Product Type dropdown changes
  $(document).on("change", ".productType", function () {
    var productTypeId = $(this).val();
    var isDisabled = $(this).is(':disabled') || $(this).data('was-disabled-by-bypass') === true;
    // Finds the wrapper row container matching your HTML class
    var container = $(this).closest(".product-entry");
    var subcategoryDropdown = container.find(".productTypeSubcategory");

    if (productTypeId && productTypeId !== "N/A") {
      subcategoryDropdown
        .prop("disabled", isDisabled)
        .html('<option value="N/A" disabled selected>Loading...</option>');

      $.ajax({
        url: "../php/subcategoryList.php",
        type: "POST",
        data: { category_id: productTypeId },
        success: function (data) {
          if (data) {
            subcategoryDropdown.html(data);

            // FIX: Pull the saved value printed by PHP out of the data attribute
            var savedValue = subcategoryDropdown.attr("data-saved-value");
            if (savedValue && savedValue !== "") {
              subcategoryDropdown.val(savedValue);
              // Clear attribute after setting so it doesn't conflict with manual modifications
              subcategoryDropdown.removeAttr("data-saved-value");
            }
          } else {
            subcategoryDropdown
              .prop("disabled", true)
              .html('<option value="N/A" disabled selected>No subcategories available</option>');
          }
        },
        error: function () {
          subcategoryDropdown
            .prop("disabled", true)
            .html('<option value="N/A" disabled selected>Error loading subcategories</option>');
        }
      });
    } else {
      subcategoryDropdown
        .prop("disabled", true)
        .html('<option value="N/A" selected disabled>Choose...</option>');
    }
  });

  // 2. FIX FOR PRE-EXISTING ROWS: Loop through each row generated by PHP on page load
  $(".product-entry").each(function () {
    var productTypeSelect = $(this).find(".productType");
    // Force the change event to fire if it already has a saved selection from the DB
    if (productTypeSelect.val() && productTypeSelect.val() !== "N/A") {
      let wasDisabled = productTypeSelect.prop('disabled');
      if (wasDisabled) {
        productTypeSelect.data('was-disabled-by-bypass', true);
        productTypeSelect.prop('disabled', false);
      }
      productTypeSelect.trigger("change");
      if (wasDisabled) {
        productTypeSelect.prop('disabled', true);
        productTypeSelect.removeData('was-disabled-by-bypass');
      }
    }
  });
});